//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string AccountNumber { get; set; }
        public System.DateTime Date { get; set; }
        public string AccountName { get; set; }
        public decimal Price { get; set; }
        public string BankName { get; set; }
        public string ForWhom { get; set; }
    }
}
