//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoordinatingCouncil
    {
        public CoordinatingCouncil()
        {
            this.Leases = new HashSet<Lease>();
            this.PurchaseLetters = new HashSet<PurchaseLetter>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public Nullable<System.DateTime> MembershipDate { get; set; }
        public string NationalCode { get; set; }
        public Nullable<System.DateTime> QuitDate { get; set; }
    
        public virtual ICollection<Lease> Leases { get; set; }
        public virtual ICollection<PurchaseLetter> PurchaseLetters { get; set; }
    }
}
