//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandLord
    {
        public LandLord()
        {
            this.Leases = new HashSet<Lease>();
            this.PurchaseLetters = new HashSet<PurchaseLetter>();
        }
    
        public int Id { get; set; }
        public int PersonalInfoId { get; set; }
        public Nullable<byte> Share { get; set; }
        public bool Type { get; set; }
        public int EstateId { get; set; }
    
        public virtual Estate Estate { get; set; }
        public virtual PersonalInfo PersonalInfo { get; set; }
        public virtual ICollection<Lease> Leases { get; set; }
        public virtual ICollection<PurchaseLetter> PurchaseLetters { get; set; }
    }
}
