//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lease
    {
        public int Id { get; set; }
        public int LandLordId { get; set; }
        public int TanentPersonalInfo { get; set; }
        public decimal Leasehold { get; set; }
        public Nullable<byte> LeaseMounth { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public decimal Charge { get; set; }
        public decimal LateCharge { get; set; }
        public int CouncilId { get; set; }
        public byte JobId { get; set; }
        public string PaymentType { get; set; }
        public decimal Prepayment { get; set; }
        public string Witness { get; set; }
        public string Code { get; set; }
        public string AmountInWords { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual CoordinatingCouncil CoordinatingCouncil { get; set; }
        public virtual LandLord LandLord { get; set; }
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
