//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public byte Id { get; set; }
        public byte RoleTypeId { get; set; }
        public int PersonalInfoId { get; set; }
    
        public virtual RoleType RoleType { get; set; }
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
